---
title: "Test_2"
author: "Insonlin"
date: "2019/7/11"
output: html_document
---

```{r}
library(downloader)
library(dplyr)
```

```{r}
url <- "https://data.taipei/api/getDatasetInfo/downloadResource?id=745b8808-061f-4f5b-9a62-da1590c049a9&rid=5012e8ba-5ace-4821-8482-ee07c147fd0a"
filename <- "Taipei City Fixed Speed Photograph Location Table.csv"
```

```{r}
if (!file.exists(filename)) download(url,filename)
A <- read.csv("Taipei City Fixed Speed Photograph Location Table.csv")
head(A)
```

```{r}
Data_A1 <- select(A, area, road, location)
head(Data_A1)
```

```{r}
url <- "https://data.taipei/api/getDatasetInfo/downloadResource?id=2f238b4f-1b27-4085-93e9-d684ef0e2735&rid=ea731a84-e4a1-4523-b981-b733beddbc1f"
filename <- "Taipei City A1 and A2 traffic accident details.csv"
if (!file.exists(filename)) download(url,filename)
```

```{r}
B <- read.csv("Taipei City A1 and A2 traffic accident details.csv")
head(B)
```

```{r}
Data_B1 <- select(B, 肇事地點)
head(Data_B1)
```

```{r}
Data<-data.frame(Area=c(Data_A1[1]), 
      Road=c(Data_A1[2]), 
      Location=c(Data_A1[3]), 
      With_Monitor=c(0),
      Without_Monitor=c(0))

Data$With_Monitor[1:139]<-0
Data$Without_Monitor[1:139]<-0
i<-0
check<-0

for (j in 1:50329){
  for (k in 1:139){
    if (grepl(Data$road[k], Data_B1$肇事地點[j])){
      if (grepl(Data$location[k], Data_B1$肇事地點[j])){
        Data$With_Monitor[k]<-Data$With_Monitor[k]+1
        check<-1
        break
      }
      else{
        check<-k
      }
    }
  }
  if (check!=1){
    i<-i+1
    Data$Without_Monitor[check]<-Data$Without_Monitor[check]+1
  }
  check<-0
}
head(i)
Data
```